import 'package:flutter/material.dart';

import '../models/planet_model.dart';

const planetCatalog = <PlanetModel>[
  PlanetModel(
    name: 'Mercury',
    orbitRadius: 96,
    orbitHeight: 30,
    orbitalSpeed: 0.78,
    size: 19,
    imageAsset: 'assets/planets/mercury.png',
    radiusLabel: '2,439.7 km',
    distanceLabel: '57.9 million km',
    orbitalSpeedLabel: '47.87 km/s',
    rotationPeriodLabel: '58.6 Earth days',
    facts: ['Smallest planet', 'A solar day lasts 176 Earth days'],
    colors: [Color(0xFFB9AA92), Color(0xFF5E5145)],
  ),
  PlanetModel(
    name: 'Venus',
    orbitRadius: 136,
    orbitHeight: 44,
    orbitalSpeed: 0.62,
    size: 27,
    imageAsset: 'assets/planets/venus.png',
    radiusLabel: '6,051.8 km',
    distanceLabel: '108.2 million km',
    orbitalSpeedLabel: '35.02 km/s',
    rotationPeriodLabel: '243 Earth days',
    facts: ['Hottest planet', 'Rotates backward'],
    colors: [Color(0xFFFFBE62), Color(0xFF8C4A1D)],
  ),
  PlanetModel(
    name: 'Earth',
    orbitRadius: 184,
    orbitHeight: 61,
    orbitalSpeed: 0.52,
    size: 30,
    imageAsset: 'assets/planets/earth.png',
    radiusLabel: '6,371 km',
    distanceLabel: '149.6 million km',
    orbitalSpeedLabel: '29.78 km/s',
    rotationPeriodLabel: '23.9 hours',
    facts: ['Only known planet with life', 'Surface is about 71% ocean'],
    colors: [Color(0xFF53A8FF), Color(0xFF12447C), Color(0xFF54B56B)],
  ),
  PlanetModel(
    name: 'Mars',
    orbitRadius: 226,
    orbitHeight: 75,
    orbitalSpeed: 0.42,
    size: 25,
    imageAsset: 'assets/planets/mars.png',
    radiusLabel: '3,389.5 km',
    distanceLabel: '227.9 million km',
    orbitalSpeedLabel: '24.07 km/s',
    rotationPeriodLabel: '24.6 hours',
    facts: ['Home to Olympus Mons', 'Has polar ice caps'],
    colors: [Color(0xFFFF7848), Color(0xFF6D2417)],
  ),
  PlanetModel(
    name: 'Jupiter',
    orbitRadius: 296,
    orbitHeight: 98,
    orbitalSpeed: 0.25,
    size: 48,
    imageAsset: 'assets/planets/jupiter.png',
    radiusLabel: '69,911 km',
    distanceLabel: '778.5 million km',
    orbitalSpeedLabel: '13.07 km/s',
    rotationPeriodLabel: '9.9 hours',
    facts: ['Largest planet', 'Great Red Spot is a giant storm'],
    colors: [Color(0xFFFFD29B), Color(0xFFB96B3F), Color(0xFFF5EFE4)],
  ),
  PlanetModel(
    name: 'Saturn',
    orbitRadius: 370,
    orbitHeight: 123,
    orbitalSpeed: 0.19,
    size: 42,
    imageAsset: 'assets/planets/saturn.png',
    radiusLabel: '58,232 km',
    distanceLabel: '1.43 billion km',
    orbitalSpeedLabel: '9.68 km/s',
    rotationPeriodLabel: '10.7 hours',
    facts: ['Most visible rings', 'Less dense than water'],
    colors: [Color(0xFFFFDFA4), Color(0xFF9E7842)],
    hasRing: true,
  ),
  PlanetModel(
    name: 'Uranus',
    orbitRadius: 440,
    orbitHeight: 146,
    orbitalSpeed: 0.14,
    size: 36,
    imageAsset: 'assets/planets/uranus.png',
    radiusLabel: '25,362 km',
    distanceLabel: '2.87 billion km',
    orbitalSpeedLabel: '6.80 km/s',
    rotationPeriodLabel: '17.2 hours',
    facts: ['Rotates on its side', 'Ice giant with methane clouds'],
    colors: [Color(0xFF7DE7EC), Color(0xFF1E7B8C)],
    hasRing: true,
  ),
  PlanetModel(
    name: 'Neptune',
    orbitRadius: 506,
    orbitHeight: 168,
    orbitalSpeed: 0.11,
    size: 38,
    imageAsset: 'assets/planets/neptune.png',
    radiusLabel: '24,622 km',
    distanceLabel: '4.50 billion km',
    orbitalSpeedLabel: '5.43 km/s',
    rotationPeriodLabel: '16.1 hours',
    facts: ['Fastest winds in the solar system', 'Deep blue ice giant'],
    colors: [Color(0xFF477BFF), Color(0xFF12266E)],
  ),
  PlanetModel(
    name: 'Moon',
    orbitRadius: 162,
    orbitHeight: 54,
    orbitalSpeed: 0.68,
    size: 21,
    imageAsset: 'assets/planets/moon.png',
    radiusLabel: '1,737.4 km',
    distanceLabel: '384,400 km from Earth',
    orbitalSpeedLabel: '1.02 km/s',
    rotationPeriodLabel: '27.3 Earth days',
    facts: ['Earth-facing side is tidally locked', 'Drives ocean tides'],
    colors: [Color(0xFFD8D8D8), Color(0xFF676767)],
  ),
  PlanetModel(
    name: 'Comet',
    orbitRadius: 270,
    orbitHeight: 84,
    orbitalSpeed: 0.34,
    size: 18,
    imageAsset: 'assets/planets/comet.png',
    radiusLabel: 'Variable',
    distanceLabel: 'Highly elliptical',
    orbitalSpeedLabel: 'Variable',
    rotationPeriodLabel: 'Irregular',
    facts: ['Leaves a glowing tail near the Sun', 'Made of ice and dust'],
    colors: [Color(0xFFE8FAFF), Color(0xFF83D8FF)],
    isComet: true,
  ),
];
